### ISSUE TITLE
[Boston Ruby Group](https://www.meetup.com/bostonrb/)

### ISSUE THREAD

**Issue by jpcamara** [ShortRuby/submit#100]
## Link to the content

[Boston Ruby Group](https://www.meetup.com/bostonrb/)

## Anything else

I noticed the Boston Ruby Group wasn't mentioned in Ruby meetups in this weeks issue. It's happening monthly again, and we've got a meetup tomorrow, July 9th.

**Comment by lucianghinda** [comment]
I am sorry I missed it. 

I will keep it close and search for it. Usually, I look at https://rubyconferences.org to get a glimpse of what's next and do a few searches on meetup.com (but somehow, I missed yours). 

May I suggest you add it to https://github.com/ruby-conferences/ruby-conferences.github.io?

**Comment by jpcamara** [comment]
> I am sorry I missed it. 
> 
> 
> 
> I will keep it close and search for it. Usually, I look at https://rubyconferences.org to get a glimpse of what's next and do a few searches on meetup.com (but somehow, I missed yours). 
> 
> 
> 
> May I suggest you add it to https://github.com/ruby-conferences/ruby-conferences.github.io? 
> 
> 

I will suggest it there, thank you!
