### ISSUE TITLE
How to Deploy a Ruby on Rails Application to Katapult Using Kamal 2

### ISSUE THREAD

**Issue by paulsturgess** [ShortRuby/submit#110]
## Link to the content
[How to Deploy a Ruby on Rails Application to Katapult Using Kamal 2](https://katapult.io/blog/post/how-to-deploy-a-ruby-on-rails-application-to-katapult-using-kamal-2/)

## Anything else
Just published today 5th Nov

**Comment by lucianghinda** [comment]
Will be included in today's edition
