### ISSUE TITLE
How we built a Ruby library that saves 50% in testing time

### ISSUE THREAD

**Issue by anmarchenko** [ShortRuby/submit#111]
## Link to the content
[How we built a Ruby library that saves 50% in testing time](https://www.datadoghq.com/blog/engineering/ruby-test-impact-analysis/)

## Anything else
Published on Nov, 1st. This is a story of developing a brand new way to collect per test coverage in Ruby to enable running tests selectively based on recent git changes.

**Comment by lucianghinda** [comment]
Will be included in today's edition
