### ISSUE TITLE
Build a Slack App with Rails

### ISSUE THREAD

**Issue by danielabar** [ShortRuby/submit#112]
## Link to the content

https://danielabaron.me/blog/rails-slack-app-part1-oauth/

## Anything else

Learn how to build a Slack application with Rails in this multi-part series. Part 1 covers setting up a new Rails app, configuring OAuth for authentication, and laying the foundation for Retro Pulse, an app designed to enhance agile retrospectives on Slack.

**Comment by lucianghinda** [comment]
Hi @danielabar this article is not from last week: 11-17 November so I could not include it in the newsletter
