### ISSUE TITLE
Copy to Clipboard with Stimulus & Rails

### ISSUE THREAD

**Issue by danielabar** [ShortRuby/submit#114]
## Link to the content

https://danielabaron.me/blog/stimulus-copy-to-clipboard/

## Anything else

Add a Copy to Clipboard button to your Rails app using Stimulus. This post shows how to mix modern JavaScript features into server-rendered Rails views.

**Comment by lucianghinda** [comment]
Hi @danielabar this article is not from last week: 11-17 November so I could not include it in the newsletter
