### ISSUE TITLE
What is the difference between Turbo and Stimulus, and what exactly is Hotwire?

### ISSUE THREAD

**Issue by sidk** [ShortRuby/submit#14]
## Link to the content
https://www.ducktypelabs.com/turbo-vs-stimulus/

## Anything else
If it has been a while since you last used Rails, you may be feeling a little lost with some of the newer, front-end focussed features that Rails has added over the years. This article gives a quick overview of what these things are, and where they fit into the bigger picture of Rails.

**Comment by lucianghinda** [comment]
Hi @sidk 

Thank you for your submission. I will include https://www.ducktypelabs.com/the-anatomy-of-a-turbo-stream in the Deep Dive section of the newsletter. It appears to me that the article you proposed is a bit older.

PS: Does your blog have an RSS feed?

**Comment by sidk** [comment]
@lucianghinda I'm just seeing this. Thank you for including my article. 

My blog does not have an RSS feed, but I can set one up.
