### ISSUE TITLE
What to do when the docs aren't enough

### ISSUE THREAD

**Issue by sidk** [ShortRuby/submit#15]
## Link to the content

https://www.ducktypelabs.com/when-docs-arent-enough/

## Anything else

Software docs (Rails, Hotwire or otherwise), are often works in progress. Even well documented projects can be sparsely documented at their edges. What are you supposed to do when they aren’t enough? This article goes over five time-tested strategies and behaviors you can use when you reach a “docs dead-end” next time.

**Comment by lucianghinda** [comment]
This will be included in today's edition in the Related section of Articles
