### ISSUE TITLE
Rails 7.1 Adds ActiveJob#perform_all_later To Enqueue Multiple Jobs At Once

### ISSUE THREAD

**Issue by sonamvg** [ShortRuby/submit#20]
## Link to the content
https://blog.saeloun.com/2023/11/27/rails-7-1-adds-active-job-perform-all-later/

## Anything else
Bring efficiency and flexibility to job enqueuing in Rails 7.1 with ActiveJob's perform_all_later. Handle diverse job arguments, support bulk enqueuing, and offer enhanced control over job execution.

**Comment by lucianghinda** [comment]
Will be included in Edition 70 (sent on 4 December 2023)
