### ISSUE TITLE
Ruby 3.3 Introduces Range#overlap? method

### ISSUE THREAD

**Issue by sonamvg** [ShortRuby/submit#24]
## Link to the content

https://blog.saeloun.com/2023/12/11/ruby-3-3-introduces-range-overlap/

Compare two ranges and see if they overlap each other with the Ruby overlap? method. It returns true if two ranges overlap each other.

## Anything else
#ruby #ruby3.3 #range #overlap #rails

**Comment by lucianghinda** [comment]
This was included in edition 72
