### ISSUE TITLE
Automate Fly Postgres Database Backup & Store To S3 bucket With GitHub Actions

### ISSUE THREAD

**Issue by sonamvg** [ShortRuby/submit#27]
## Link to the content
https://blog.saeloun.com/2023/12/20/automating-fly-db-backup-with-github-actions/

## Anything else
Discover how GitHub Actions empowers automation to effortlessly backup Fly.io hosted Postgres databases, saving backups to a designated S3 bucket.

#fly #automate #postgres #backup #githubactions

**Comment by lucianghinda** [comment]
This will be included in today's edition 73
