### ISSUE TITLE
Ruby 3.3 Implements Range#reverse_each Method For Very Large or Beginless Ranges And Error Handling For Endless Ranges

### ISSUE THREAD

**Issue by sonamvg** [ShortRuby/submit#30]
## Link to the content
https://blog.saeloun.com/2024/01/09/ruby-3-3-range-reverse-each-for-begin-endless-ranges/

## Anything else
With Ruby 3.3, Range#reverse_each can now process very large or beginless ranges with an Integer endpoint and raises TypeError for endless ranges.

#ruby3.3 #ruby #range #range_reverse_each #reverse_each

**Comment by lucianghinda** [comment]
Unfortunatelly this did not managed to be included as that newsletter - the first one after holidays had a lot to cover and I had to cut a lot more.

Saeloun is a blog that I include often as you cover very well what's new in Ruby and Rails so I am sorry I was not able to include this one.

**Comment by sonamvg** [comment]
Hi!
No worries. I can understand.
Thanks for including our blogs.
