### ISSUE TITLE
[Rails flash messages and UX]

### ISSUE THREAD

**Issue by bdavidxyz** [ShortRuby/submit#31]
## Link to the content

https://bootrails.com/blog/rails-flash-messages-and-ux/

## Anything else

It's the English transcription of a ParisRB conference I gave this month.

So it's more an introduction to the accessibility of Flash messages, because achieve it properly is quite tricky.

But for anyone interested to a very old notion of Rails (flash messages), it's still has value (I hope!)

**Comment by lucianghinda** [comment]
This will be included in today's edition - 75
