### ISSUE TITLE
[Tailwind and Ruby-on-Rails starter kit]

### ISSUE THREAD

**Issue by bdavidxyz** [ShortRuby/submit#32]
## Link to the content

https://bootrails.com/blog/rails-and-tailwind-starter-kit/

## Anything else

Yes, I know, starter kits are all the rage nowadays, but I needed something backed by a full Tailwind "framework".

The repository is here : https://github.com/bdavidxyz/tailstart

**Comment by lucianghinda** [comment]
This will be included in today's edition 75
