### ISSUE TITLE
Rails 7.1 Adds path_params Option For url_for Helper Method

### ISSUE THREAD

**Issue by sonamvg** [ShortRuby/submit#33]
## Link to the content
https://blog.saeloun.com/2024/01/16/rails-7-1-path_params_option_for_url_for_method/

## Anything else
With Rails 7.1, the path_params option for the url_for helper method allows specified params to be used exclusively for named segments under scoped routing without unnecessarily appending parameters to every URL.

#rails #rails7.1 #url_for #path_params #railsrouting #routing #scopedrouting

**Comment by lucianghinda** [comment]
This will be included in today's edition 75
