### ISSUE TITLE
Rubygems introduced a file option to specify Ruby version in Gemfile

### ISSUE THREAD

**Issue by sonamvg** [ShortRuby/submit#34]
## Link to the content
https://blog.saeloun.com/2024/01/17/rubygems-introduced-a-file-option-to-specify-ruby-version/

## Anything else
Rubygems introduced a file option to specify Ruby version in Gemfile

#ruby #rubygem

**Comment by lucianghinda** [comment]
I have not included this in today's edition. When Rubygems announced this it was covered pretty well I think

**Comment by sonamvg** [comment]
Sure! Thanks
