### ISSUE TITLE
[How to encode an URL String in Ruby - 2024 edition]

### ISSUE THREAD

**Issue by bdavidxyz** [ShortRuby/submit#39]
## Link to the content

https://bootrails.com/blog/how-to-encode-url-string-in-ruby/

## Anything else

Fresh version of a classic problem - URL encoding in Ruby. I recently had the problem - here is how I solved it :)

**Comment by lucianghinda** [comment]
This will be included in today's edition

**Comment by bdavidxyz** [comment]
Thanks Lucian!

Le lun. 29 janv. 2024 à 05:14, Lucian Ghinda ***@***.***> a
écrit :
