### ISSUE TITLE
[Link] Self-Hosted GitHub Actions Runners with Hatchbox

### ISSUE THREAD

**Issue by stevegeek** [ShortRuby/submit#40]
## Link to the content
https://www.diaconou.com/blog/self-hosted-github-actions-runners-with-hatchbox/

## Anything else
"A guide on setting up Hatchbox AWS EC2 servers as self-hosted GitHub Actions runners, including using Linux ARM64 machines"

Not sure if this is too niche for the newsletter but if you think it would be interesting to others then here it is!

**Comment by lucianghinda** [comment]
This will be included in today's edition
