### ISSUE TITLE
Hanami shrine

### ISSUE THREAD

**Issue by krzykamil** [ShortRuby/submit#83]
## Link to the content
https://2n.pl/blog/hanami-shrine-file-handling-in-hanami

## Anything else
My implementation of shrine.rb in hanami web framework. It has some caveats due to usin ROM-rb as ORM, but it only makes it more interesting, showing of shrine superior flexibility and simplicity over ActiveStorage.

**Comment by lucianghinda** [comment]
Included in today's edition - Short Ruby Newsletter 91
