### ISSUE TITLE
Ruby 3.4, No More TypeError With **nil As It Is Treated As An Empty Hash.

### ISSUE THREAD

**Issue by sonamvg** [ShortRuby/submit#84]
## Link to the content

Ruby 3.4, No More TypeError With **nil As It Is Treated As An Empty Hash.

https://blog.saeloun.com/2024/05/13/ruby-3-4-no-more-type-error-with-nil/

**Comment by lucianghinda** [comment]
Included in today's edition - Short Ruby Newsletter 91
