### ISSUE TITLE
Concurrency and parallelism in Ruby 💎

### ISSUE THREAD

**Issue by Mth0158** [ShortRuby/submit#85]
## Link to the content
[https://mathieu-eustachy.com/articles/concurrency-and-parallelism-in-ruby?locale=en](https://mathieu-eustachy.com/articles/concurrency-and-parallelism-in-ruby?locale=en)

## Anything else
It looks like a philosophy essay title, but they are fundamental developing principles.

Is parallelism always better than concurrency? What’s the main differences between the two? How do they apply to the Ruby world?

This article I have written will teach these points. Plus you will be able to decrypt the puma.rb configuration file in your Rails app. The article is the 3rd one of an article series about “low-level” computing concepts applied to Ruby.

**Comment by lucianghinda** [comment]
Included in today's edition - Short Ruby Newsletter 91
